
language: java

before-script: cd Release

deploy:
  edge: true
  provider: cloudfoundry
  username: hydsri.kiran@gmail.com
  password: asdf1234
  api: https://api.run.pivotal.io
  organization: VERIZON
  space: staging